spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  web:
    resources:add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8080

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: a91fa9864d6b594c1526c5eb334694650482032a07323f52b586a8d9ed698241ff4d60b2b8b1b49f248a180e2c108a160a3227f83580c8def7ba1646f835be9110c84e9afa8b4a3da3affbc2e2772d8b4725ede1ca9cbb81e054f09b7157162a5d55aee39deef771b0eb55a6db2cd66b239db895283b44653f06e
  refresh-token:
    expirationInMils: 600000
  admin:
    password: 'nimda123'
    email: 'super.admin@email.com'




