services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: sport_navigator
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - sport-navigator
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  sport-navigator:
    driver: bridge


volumes:
  postgres:
    driver: local
