services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: sport_navigator
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - sport-navigator
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'


networks:
  sport-navigator:
    driver: bridge


volumes:
  postgres:
    driver: local
